### ISSUE TITLE
Unable to start game: not enough teleportation spots.

### ISSUE THREAD

**Issue by DrSnikerFreak** [zDevelopers/UHPlugin#101]
I keep getting this error when i try to start uhc. I generated 4 different worlds to see if that was an issue but i keep getting the same error.

**Comment by jonyroda97** [comment]
i've you used the <code>/uh spawns</code> to generate them?

**Comment by jonyroda97** [comment]
You need to add the spawn points by in-game/console command or in the config file where it says "spawnpoints".
You can generate all of the wanted spawn points by using the <code>/uh spawns generate</code> and changing the parameters that are required for your own needs.

If need any help to do this just say :smiley:

**Comment by AmauryCarrade** [comment]
It's, yes, not a real bug, but in fact we could automatically generate the spawn points (if not generated) when the game starts...

**Comment by DrSnikerFreak** [comment]
that would be really great if you can add that
