### ISSUE TITLE
Plugin doesn't work as it is supposed to.

### ISSUE THREAD

**Issue by Sprucecodes** [zDevelopers/UHPlugin#105]
Hi, when I downloaded your plugin and tried running it it came out with an error and the commands that are working is :
![2015-06-10_12 39 44](https://cloud.githubusercontent.com/assets/12383642/8080566/e110f168-0f6d-11e5-8f3b-0672c90d99f0.png)

And here is the error :
http://pastebin.com/x9EB7fM3

I do not know what is wrong and if you need a plugin list I can send it to you. I do not want to post them public.

Please help as soon as you can. Thanks in advance.

(Sorry if I spelled anything wrong English is not my foreign language)

**Comment by AmauryCarrade** [comment]
Are you using the correct version of [ProtocolLib](http://www.spigotmc.org/resources/protocollib.1997/)?

(Btw you can speak French, it's my native language.)

**Comment by Sprucecodes** [comment]
I'm using the latent version of ProtocolLib. Is that compatible?

**Comment by jonyroda97** [comment]
About the image: use <code>/uh</code> to see the rest of the plugin commands.
