### ISSUE TITLE
World border on Nether crashes plugin

### ISSUE THREAD

**Issue by jonyroda97** [zDevelopers/UHPlugin#107]
<blockquote>I found one bug (in case it is a bug). If you set a world border for the nether, the plugin crashes as soon as someone goes into the nether.</blockquote>
Reported by [waytearp](http://dev.bukkit.org/profiles/waytearp/) on [Bukkit Dev](http://dev.bukkit.org/bukkit-plugins/uhc/?comment=227).<br>
Is it UHCReloaded or WorldBorder fault?

**Comment by AmauryCarrade** [comment]
Probably WorldBorder, but I'll check that.

http://dev.bukkit.org/bukkit-plugins/uhc/?comment=230

**Comment by ElDude1** [comment]
I have to admit that I am unable to reproduce this "bug" when hosting a server on my local machine, so you probably don't have to look into it, as it seems to be a problem with our server. I will do some more tests on my online server.
