### ISSUE TITLE
Allow Players to "register" and return.

### ISSUE THREAD

**Issue by jdtzmn** [zDevelopers/UHPlugin#115]
Enhancement:
You should be able to register a spot in a game before it starts. The problem is that when you join the server and /join onto a team, if you are not on the server when someone runs '/uh start', then you will be in spectator when you rejoin. I want players to be able to register and then leave, and not have to worry about getting into the game at a set time.

Example of how to implement:
Make a countdown scoreboard and players will join teams during the countdown and when the countdown is up, the game will start, but players don't have to be online to be in the game. A player could join during countdown, type '/join orange', leave the server, come back after the count down is up, and still be allowed to play.

**Comment by AmauryCarrade** [comment]
Possible, not so hard to implement I think; but, what to do when a player first join the game? Teleportation to the team's spawn point? To a random player (may be dangerous)?

Only for first-joining players of course.

**Comment by jdtzmn** [comment]
make an option for teleporting somewhere inside the border, or teleporting to the default team spawnpoint

**Comment by AmauryCarrade** [comment]
I implemented a `/uh tpspawn` command, to manually teleport a player to his spawn point.

A spawn point is assigned to any player registered (i.e. in a team), even if offline when the game starts. This command can teleport the player to his assigned spawn point.

This don't support solo games, but for these ones, it's simpler to teleport the player to a random high spot in creative and put it back in survival after, I think. But this may evolve, comment or reopen if you disagree.
