### ISSUE TITLE
UHCReloaded + PermissionsEX // How to make the little team colored circle appear next to your name?

### ISSUE THREAD

**Issue by mike70387** [zDevelopers/UHPlugin#118]
Hello, I was wondering how you could get the team indicator icon next to your name when you are using PermissionsEX. What I mean by this is my chat is like this currently: http://prntscr.com/8ngpfp but I'd like to make it like this: http://prntscr.com/8ngpkh (The dot with the team color, then a prefix/name or just colored name. Does this have to do with my essentials chat formatting? Please reply!

**Comment by AmauryCarrade** [comment]
This is currently not possible. You can color the name following the team, but nothing more currently (it changes the player's display name).

By the way, the dot in the screenshot represents the online status of the player (green or gray).
