### ISSUE TITLE
Personnalisation du nom de l'équipe + autre proposition

### ISSUE THREAD

**Issue by YoLaw** [zDevelopers/UHPlugin#122]
Bonjour Amaury, 
je viens de me rendre compte que vous êtes français donc autant s'exprimer en français!
Je me disais en organisant des UHC que le nom de l'équipe devrait être personnalisable PAR les joueurs de l'équipe... Par exemple un joueur qui rejoint une équipe pré faite en premier pourra en changer son nom avec une commande type /uh rename <nom>... 
Ou dans le meilleur des cas donner un item à chaque joueurs afin qu'ils créent eux même leur équipe. Ce concept existe dans le plugin More Difficulties (disponible sur DevBukkit)... 

J'ai une deuxième proposition qui peut être vraiment pratique! 
Je m’aperçoit qu'a la fin de mes parties quand il reste une seule équipe (ou joueur) en vie, il n'y a pas le message de victoire et les commandes automatiques de fin pour la simple et bonne raison que des personnes se sont déconnectées, et considérées comme toujours vivantes... Il serait pratique d'ajouter une option comme quoi le joueur serait considéré comme mort au bon de X temps d'absence (Personnalisable dans config.yml), avec éventuellement une commande bypass faite par l'administrateur qui autoriserait le joueur à s'absenter exceptionnellement plus longtemps que la limite... 
Merci de votre réponse! :)

**Comment by AmauryCarrade** [comment]
> Je me disais en organisant des UHC que le nom de l'équipe devrait être personnalisable PAR les joueurs de l'équipe... Par exemple un joueur qui rejoint une équipe pré faite en premier pourra en changer son nom avec une commande type /uh rename ...
Ou dans le meilleur des cas donner un item à chaque joueurs afin qu'ils créent eux même leur équipe. Ce concept existe dans le plugin More Difficulties (disponible sur DevBukkit)... 

J'y avais déjà pensé. Je vais voir si je vais le faire, mais il y a des chances, étant donné que je suis en train de re-réfléchir à comment refondre le système d'équipes pour qu'il soit plus modulable autant pour les joueurs que pour l'administrateur.

> Je m’aperçoit qu'a la fin de mes parties quand il reste une seule équipe (ou joueur) en vie, il n'y a pas le message de victoire et les commandes automatiques de fin pour la simple et bonne raison que des personnes se sont déconnectées, et considérées comme toujours vivantes... Il serait pratique d'ajouter une option comme quoi le joueur serait considéré comme mort au bon de X temps d'absence (Personnalisable dans config.yml), avec éventuellement une commande bypass faite par l'administrateur qui autoriserait le joueur à s'absenter exceptionnellement plus longtemps que la limite...

Il existe déjà `/uh kill <pseudo>` qui sert précisément à cela. L'automatiser après un certain délai ? Pourquoi pas. Je note.

**Comment by YoLaw** [comment]
Super merci! :) 
Et merci pour ce gros boulot que tu fais... Quand on configure bien et qu'on l'associe aux bons plugins, UHPlugin nous offre vraiment une très large carte de personnalisation!! 
Petite remarque mise à part, avec les snapshots au démarrage du serveur, le fichier de langues se remet automatiquement... J'ai reglé le problème sur mon PC et sur mon FTP en le mettant en lecture seule mais bon voilà c'est un peu chiant parfois... :)

**Comment by AmauryCarrade** [comment]
>Petite remarque mise à part, avec les snapshots au démarrage du serveur, le fichier de langues se remet automatiquement... J'ai reglé le problème sur mon PC et sur mon FTP en le mettant en lecture seule mais bon voilà c'est un peu chiant parfois... :)

Si vous modifiez la clef `version` du fichier `manifest.yml` dans le dossier des langues en la version courante (`1.3 §cdev` par exemple), les fichiers ne devraient plus être réécrit.
Ce système est présent pour mettre les fichiers à jour lorsque la version change, et differt volontairement de la version courante pour justement, dans le cadre du développement, les réécrire systématiquement.

**Comment by AmauryCarrade** [comment]
1. `/teams`
2. ![Bouton renommer](http://raw.carrade.eu/s/1452640887.png)
3. ![Champ de renommage](http://raw.carrade.eu/s/1452640951.png)
4. ???
5. Profit!

**Comment by YoLaw** [comment]
Génial! Bravo! :dancer:
