### ISSUE TITLE
Unable to start game: Not enough teleportation spots. I dont know!?!??

### ISSUE THREAD

**Issue by JamieChanTV** [zDevelopers/UHPlugin#123]
THIS IS URGENT, AND NEEDS TO BE SOLVED BY FRIDAY.

Ok so I have seen another issue like this but it wasnt really solved.
It said we have to do /uh spawns generate to fix it. But im really confused on how to do it!
/uh spawns generate confuses me so much. So if you would please solve how to do it. This is for 11 teams of 2. A world called ChristmasUHCsAreBae. A world of 1500 block radius (size, square). And /uh generatewalls has already been run.

Please tell me the exact command I need to do, just put all the things like team spacing and "count" on default <3

**Comment by AmauryCarrade** [comment]
In short, from in-game, in the good world, supposing that:
- you want random spawn points;
- the spawn of the world is the center of the map:

```
/uh spawns generate random 1400 250 11
```

But if you already created the teams and configured the world size, you can just execute:
```
/uh spawns generate random
```
and the generator will use the teams count as spawns count, and the map size.
