### ISSUE TITLE
[IMPORTANT] /uh start slow

### ISSUE THREAD

**Issue by YoLaw** [zDevelopers/UHPlugin#124]
Bonjour,
en faisant une partie de UHC avec mes potes (26) j'ai voulu faire /uh start slow mais ca a fait le meme effet qu'un /uh start... Très ennuyeux car ca a fait crash mon serveur 2 fois!...
Merci pour ce problème! :)
PS: J'utilise la dernière snapshot (#249).

**Comment by AmauryCarrade** [comment]
Dans les dernières versions, comme précisé dans `/uh start help`, la commande n'est plus `/uh start slow` mais `/uh start slow:true`, pour permettre l'ajout d'autres modificateurs (en l'occurrence, `ignoreTeams:true`).

**Comment by YoLaw** [comment]
Ah d'accord! Merci pour l'info!
