### ISSUE TITLE
Activation du PVP avant le lancement de la partie (Salle d'attente)

### ISSUE THREAD

**Issue by YoLaw** [zDevelopers/UHPlugin#125]
Bonjour,
J'aurais aimé savoir s'il est possible d'activer le pvp avant le début de la partie? J'aimerais l'activer pour mes salles d'attente.
Merci! :)

**Comment by AmauryCarrade** [comment]
Pas possible actuellement mais ça peut s'envisager.

**Comment by YoLaw** [comment]
D'accord! Dommage! :/
