### ISSUE TITLE
Problème portails nether...

### ISSUE THREAD

**Issue by YoLaw** [zDevelopers/UHPlugin#126]
Bonjour! 
Premièrement, ENORME compliment sur les 2 derniers builds de UHPlugin c'est vraiment extra en fonctionnalités! :+1: 
J'ai beaucoup aimé la fonction pour réduire la map automatiquement, cependant un problème persiste...
Prenons le cas où le jeu a démarré, et la bordure n'a pas commencé à se réduire. Un joueur, non loin de la limite de la carte construit un portail vers le nether. Il y passe un certain temps, et pendant ce temps, la limite a commencé à se réduire... Il retrouve son portail pour retourner dans l'overworld, mais quand il l'emprunte, il se retrouve complètement en dehors de la map et il meurt bêtement... 
C'est vraiment très problématique! De plus les portails peuvent être liés entre eux et donc on peut revenir sur un portail hors map...
L'idéal serait de désactiver tous les portails en dehors de la map et en faire respawner un à une distance x de la bordure mobile... Vu tout ce que vous avez ajouté à votre plugin, je pense que cela devrait être possible! :)
Merci et encore bravo!!

**Comment by AmauryCarrade** [comment]
[J'ai fait un plugin pour ça](https://github.com/AmauryCarrade/SafePortals), que j'utilise quand la réduction est activée.

**Comment by YoLaw** [comment]
Ce plugin ne semble pas fonctionner j'ai plusieurs erreurs dans la console de mon serveur... :/

**Comment by AmauryCarrade** [comment]
Possible d'ouvrir un ticket sur son dépôt avec les erreurs rencontrées ? Je l'ai utilisé récemment avec Spigot 1.8.8 sans problème, et il devrait marcher avec Bukkit 1.8+.

**Comment by YoLaw** [comment]
Perso j'utilise spigot 1.8... Je ne sais pas si ça a un lien^^

**Comment by AmauryCarrade** [comment]
Y'a pas de raison que ça marche moins normalement. Mais je ne peux rien dire de plus sans ce qu'à raconté la console, dans un ticket dans le dépôt de l'autre plugin histoire de rester organisé :) .

**Comment by YoLaw** [comment]
Je fais ça de suite ;)
