### ISSUE TITLE
Team GUI permissions

### ISSUE THREAD

**Issue by YoLaw** [zDevelopers/UHPlugin#128]
Bonjour, 
Encore une fois de superbes mises à jour, mais j'aimerais savoir quelles sont l'intégralité des permissions utiles pour que n'importe quel joueur ait accès au GUI! :)
Merci! :)

**Comment by AmauryCarrade** [comment]
- `uh.team.gui` pour pouvoir ouvrir le GUI (via `/uh team gui` ou `/teams` ; 
- les permissions `uh.player` (`uh.player.<join|leave>.<self|others>`, `uh.player.<join|leave>.*`, `uh.player.*`) pour rejoindre ou quitter les équipes ;
- la classique permission `uh.team` pour gérer les équipes via le GUI (création, suppression, modification).

**Comment by YoLaw** [comment]
D'accord merci! :)

**Comment by YoLaw** [comment]
Re-Bonjour, petite précision concernant ces permissions, est il possible d'avoir une permission pour seulement créer une équipe? Parce que si un joueur peut créer une équipe, il peut gérer toutes les autres y compris les supprimer/renommer etc.. Et ça peut être assez discordieux sur un serveur multi... :/ Merci! :)
