### ISSUE TITLE
Json code displayed in the action bar

### ISSUE THREAD

**Issue by TiTo-418** [zDevelopers/UHPlugin#132]
#### Environment

* **Minecraft version**: 1.8.8
* **Plateform used**: Spigot
* **Bukkit or Spigot version**: http://prntscr.com/b1lxvj
* **Plugin version**: http://prntscr.com/b1ly1d
* **Plugin build number**: http://prntscr.com/b1ly1d

#### Problem description

![](http://i.imgur.com/RTBZyTK.png)

#### Steps to reproduce

```
/uh start slow:true
```

**Comment by AmauryCarrade** [comment]
This should be fixed (as far as I tested); reopen if it's not for you.

**Comment by TiTo-418** [comment]
@AmauryCarrade mmm... http://prntscr.com/b2akml

**Comment by AmauryCarrade** [comment]
These chat packets are crazy.

**Comment by AmauryCarrade** [comment]
It should be OK now.

**Comment by pgmann** [comment]
Done.
