### ISSUE TITLE
/uh commands not showing up

### ISSUE THREAD

**Issue by Dunxter** [zDevelopers/UHPlugin#138]
* **Minecraft version**: 1.10.2 
* **Plateform used**: Spigot
* **Bukkit or Spigot version**: -
* **Plugin version**: 1.2
* **Plugin build number**: --

#### Problem description

When i use the /uh command it shows the next message:

/uh <subcommand> - see /uh for available subcommands.

When i use subcommands the same. Just cant use it.

#### Steps to reproduce

I dont know how i got here, no esceptions or issues in the config and the prompt files.

**Comment by AmauryCarrade** [comment]
Try with the [latest builds](https://jenkins.carrade.eu/job/UltraHardcoreReloaded/lastSuccessfulBuild/). The 1.2 is no longer directly supported due to huge code changes.
