### ISSUE TITLE
Add minPlayersPerTeam option

### ISSUE THREAD

**Issue by TheIronMinerLv** [zDevelopers/UHPlugin#143]
Hello!

Could you add a "minPlayersPerTeam" option in configuration? So it would be possible to force players in at least 2 player teams, even if game starts with some players without teams, they would be randomly sorted in 2 teams.

I don't know what would happen if in server would be odd number of players (9, for example), maybe then game just wouldn't start...

My goal would be to create "random" team select, basically players join (they can't select teams) and when game starts, server sorts them in 2 player teams.

**Comment by AmauryCarrade** [comment]
This is closely related to options added for #18, so I'll mark that as a duplicate and concentrate efforts there :) .
