### ISSUE TITLE
Is it poissible to change the "KILL THE PATRICK" trough the game, not through the config file?

### ISSUE THREAD

**Issue by JoeyFreak** [zDevelopers/UHPlugin#150]
Is it poissible to change the "KILL THE PATRICK" trough the game, not through the config file?

**Comment by Jenjeur** [comment]
If you mean “by changing only the code to avoid to use any configuration file”, yes, by changing the default value here and recompiling the plugin:



https://github.com/zDevelopers/UHPlugin/blob/8eca8138fe362f51900eb8a7129db361b1d7e656/src/main/java/eu/carrade/amaury/UHCReloaded/UHConfig.java#L99



If you mean “by using a command”, then no. What would be your usage for that?
