### ISSUE TITLE
[1.8] Add a way to display episodes ends using /title

### ISSUE THREAD

**Issue by AmauryCarrade** [zDevelopers/UHPlugin#27]

**Comment by Amunak** [comment]
Would this also show a "game start" when you start the game, possibly with countdown and stuff? That would be awesome. Also game end, announcing winner/winning team.

**Comment by AmauryCarrade** [comment]
Was planned but not written here :) .

**Comment by Relicum** [comment]
Ohpps I forgot to tell you I have code a 4K line API dedicated to Titles/Action bar and Tab Header and Footer. It will only work on the full 1.8 spigot / bukkit . Also its coded in Java 8 so unless you use Java 8 it won't be of much use. It is fully documented and been running for 6 weeks on servers with no probs. Let me know if you use java 8,  it wouldn't make a difference provided the end user was running java 8 on their server. Let me know. Sorry for forgetting about this.

**Comment by AmauryCarrade** [comment]
Ohh, this can be interesting! No problem for the only-real-1.8 support, the next version will not be compatible with 1.7.9 anyway.
But I'm currently compiling with Java 7 because a lot of servers use Java 7. Your API cannot work with Java 7?
