### ISSUE TITLE
Administrators are able to “spy” all the private team-chats

### ISSUE THREAD

**Issue by jonyroda97** [zDevelopers/UHPlugin#90]
The Global chat and ALL the Team chats.
By in-game command.

**Comment by AmauryCarrade** [comment]
Already the case with `/togglechat <teamName>` no? Or you mean all the private chats received by the administrator (on/off with a command, off by default)?

**Comment by jonyroda97** [comment]
The second one :P

**Comment by AmauryCarrade** [comment]
Hmm, this can be useful, yes.

An idea for the name of this command?

**Comment by jonyroda97** [comment]
/uh spy [on|off] ? when used without on|off it switches?

**Comment by AmauryCarrade** [comment]
`/uh team spy [player]` is good too.

I totally forgot to implement this in the public version, this is now fixed (I exceptionally implemented the spy mode in a private version because @jonyroda97 needed it in a short delay).
