### ISSUE TITLE
Episodes/Border Warning Scoreboard Time Glich

### ISSUE THREAD

**Issue by jonyroda97** [zDevelopers/UHPlugin#96]
When the command <code>/uh border warning</code> is used and it equals the time that is on the episodes, the border warning timer doesn't appear and just stays there the episodes timer and below it the text of the border warning.
There's some way too force it to appear?

**Comment by AmauryCarrade** [comment]
I will be able to fix that with the future new packet-based scoreboard system.

In the current system I cannot fix that, because of the 16-characters limit of a scoreboard text (and the length of the text for the timers displayed with hours (« `hh:mm:ss` ») is... 16 characters).
